Update scheduled_task.yml

diff --git a/.github/workflows/scheduled_task.yml b/.github/workflows/scheduled_task.yml
--- a/.github/workflows/scheduled_task.yml
+++ b/.github/workflows/scheduled_task.yml
@@ -37,10 +37,24 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          
+
+      - name: Install YDB CLI
+        run: |
+          curl -sSL https://storage.yandexcloud.net/yandexcloud-ydb/ydb-linux-amd64 -o ydb
+          chmod +x ydb
+          sudo mv ydb /usr/local/bin/
+
+      - name: Verify YDB Installation
+        run: which ydb || echo "YDB CLI not found"
+
+      - name: Install jq (for JSON parsing)
+        run: sudo apt-get update && sudo apt-get install -y jq
+
       - name: Authenticate with YDB
         run: |
+          echo '${{ secrets.YDB_AUTH_KEY }}' > authorized_key.json
           export IAM_TOKEN=$(curl -s -d "@authorized_key.json" "https://iam.api.cloud.yandex.net/iam/v1/tokens" | jq -r .iamToken)
+          echo "IAM_TOKEN=${IAM_TOKEN}" >> $GITHUB_ENV
 
       - name: Run Script
         env:
@@ -55,4 +69,5 @@ jobs:
           YDB_DATABASE: ${{ secrets.YDB_DATABASE }}
           AUTHORIZED_KEY_PATH: "./authorized_key.json"
           LOG_FILE_PATH: "./logs/logging.log"
+          IAM_TOKEN: ${{ env.IAM_TOKEN }}
         run: python main.py
